# Generated by Django 3.2 on 2021-08-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crownpack_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reg_no',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(max_length=64, unique=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.TextField(unique=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.TextField(unique=True, verbose_name='Registration No'),
        ),
    ]
